// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_o4u8rzrA1B5EUiEfdwtnKKb0zzDfIzM',
    appId: '1:861411497886:web:c7706b74fb1f5c47fca88f',
    messagingSenderId: '861411497886',
    projectId: 'auth-mini-project-iot',
    authDomain: 'auth-mini-project-iot.firebaseapp.com',
    storageBucket: 'auth-mini-project-iot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk5229Tu5bcBHWFfEnn-YS9F2rMe5Z_q4',
    appId: '1:861411497886:android:2ff9228ae552b0f6fca88f',
    messagingSenderId: '861411497886',
    projectId: 'auth-mini-project-iot',
    storageBucket: 'auth-mini-project-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKafQ0Myyq10EzygHIYQgvYMkancMcHs4',
    appId: '1:861411497886:ios:53c62175ae8a3739fca88f',
    messagingSenderId: '861411497886',
    projectId: 'auth-mini-project-iot',
    storageBucket: 'auth-mini-project-iot.appspot.com',
    iosBundleId: 'com.example.btlIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKafQ0Myyq10EzygHIYQgvYMkancMcHs4',
    appId: '1:861411497886:ios:53c62175ae8a3739fca88f',
    messagingSenderId: '861411497886',
    projectId: 'auth-mini-project-iot',
    storageBucket: 'auth-mini-project-iot.appspot.com',
    iosBundleId: 'com.example.btlIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_o4u8rzrA1B5EUiEfdwtnKKb0zzDfIzM',
    appId: '1:861411497886:web:72298ef486dea09cfca88f',
    messagingSenderId: '861411497886',
    projectId: 'auth-mini-project-iot',
    authDomain: 'auth-mini-project-iot.firebaseapp.com',
    storageBucket: 'auth-mini-project-iot.appspot.com',
  );

}